detection_class:     'person'
null_classname:      'null'

confidence_threshold: 0.7
pca_components:       30

classifier_model:    'models/classifier.p'
decomposition_model: 'models/decomposition.p'

caffe_prototype:     'models/mobilenet_ssd.prototxt'
caffe_model:         'models/mobilenet_ssd.caffemodel'
